name: Bug Report
description: Report a bug in ace
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: ace version
      placeholder: "0.1.0-snapshot.2"
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: "20.x"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
